### ISSUE TITLE
Blurry in Wayland with fractional scaling

### ISSUE THREAD

**Issue by meybonomme** [Nokse22/Exhibit#10]
Without fractional scaling:

![Screenshot from 2024-06-08 12-37-01](https://github.com/Nokse22/Exhibit/assets/147217565/b31da868-de96-4836-9cd1-9f6c92107b72)

With fractional scaling:

![Screenshot from 2024-06-08 12-37-40](https://github.com/Nokse22/Exhibit/assets/147217565/ed6f5d8e-ee32-4700-9567-103346b84d46)

**Comment by rien333** [comment]
Yeah, maybe the idea to use xwayland by default needs some further discussion/clarification.

I believe the rationale is to not leave anyone out. A fine goal, but it does raise the question who's being left out. 

Most distros that ship gnome don't offer an option to run x11 sessions anymore, iirc (e.g. fedora and maybe arch). On arch, I wouldn't even know how to start one. In that sense, you are aiding the - maybe overly change reluctant - minority, possibly at cost of the UX of the majority (this issue being one example thereof).

Moreover, this is a new app, made to look modern/GTK4-ish. In  that sense, it's realistically an early adaptors kind of thing, i.e. your users might well be the sort of people that have been using wayland for a while now.

Anyway, I was looking for something like this, so the project is much appreciated!

**Comment by rien333** [comment]
Well, I suppose the disclaimer only applies to the flatplak release. 

It doesn't take a lot of effort to package this with wayland support on Arch Linux (which I'm doing now).

**Comment by Nokse22** [comment]
Thank you, I was hoping to get some feedback on this actually.
My intention was exactly to not exclude anyone. I could switch the Flatpak version to Wayland and provide an X11 only build using github actions.

I will think about it, and test how it runs on Wayland only.

**Comment by rien333** [comment]
Well, it seems you are working on getting this fixed upstream, so I guess you're fine for the time being.

**Comment by meybonomme** [comment]
> I could switch the Flatpak version to Wayland and provide an X11 only build using github actions.

I believe that would be the best solution. As @rien333  said, it's still a modern GTK4 libadwaita application, and most mainstream Linux distributions with GNOME desktop already use Wayland.

**Comment by meybonomme** [comment]
Unfortunately issue is not gone and app version 1.20 (flatpak) is still blurry under the Wayland.

**Comment by Nokse22** [comment]
Now it is using the default GTK renderer
