### ISSUE TITLE
USD not work

### ISSUE THREAD

**Issue by Luxor95** [Nokse22/Exhibit#13]
It looks like USD is not loading in the app. I tried with a USD test scene [Kitchen Set](https://openusd.org/release/dl_kitchen_set.html) provided by Pixar. As well as with a model created in a blender and exported to USD.

![image](https://github.com/Nokse22/Exhibit/assets/63251682/f9f204c4-1803-47f1-9d4b-ca285fc5c084)

**Comment by Nokse22** [comment]
Than you, I noticed just now that I didn't build the library with USD support, even if it supports it. I tried, but I'm having problems, hopefully I can add supports for USD in the next release.

**Comment by Luxor95** [comment]
Great, thanks for your work. Overall, a very nice app. It will definitely be useful for me.
