### ISSUE TITLE
Unable to create a GL context

### ISSUE THREAD

**Issue by Damond5** [Nokse22/Exhibit#14]
Hey and cheers for the work! Hoping this can be a default tool in my box.

I installed the flatpak from flathub.org, tried to load this file and got "Unable to create a GL context":

https://we.tl/t-1IMDHKPgjY

Then I tried to load some step files and I'm getting the same error every time:

![unable-to-create-a-gl-context](https://github.com/Nokse22/Exhibit/assets/34939148/a8811c2d-d615-4963-aad6-a4ddc7d3cf19)

For example this step file:

https://we.tl/t-24gbSOy2Md

Terminal output:

![terminal-output](https://github.com/Nokse22/Exhibit/assets/34939148/0fc4094e-1868-49de-ad76-390b2ca954b3)

**Comment by Nokse22** [comment]
Hello, thank you. Could you share some information about your system?

**Comment by Nokse22** [comment]
You can try setting this enviroment variable `GDK_DEBUG=gl-disable-gles` or `GDK_DEBUG=gl-prefer-gl`. It is a bug in Gtk with NVidia GPUs.

Use `flatpak override --env=VARIABLE_NAME=VARIABLE_VALUE full.application.Name` or Flatseal

**Comment by Damond5** [comment]
Thank you for the quick response!

I'm traveling for a couple of days, will have to try when I'm back at my Nvidia desktop.

________________________________

**Comment by theksepyro** [comment]
I ran into the same issue (also using an nvidia GPU) and have tried using both of those two environment variables in flatseal. The "Unable to create a GL context" message has gone away for me, but now it is just a black screen.

![Exhibit Example](https://github.com/Nokse22/Exhibit/assets/42880340/39f84d51-4372-4fd0-809c-b2bd649386be)

**Comment by Nokse22** [comment]
@theksepyro thank you! Is there any error if you run the app with `flatpak run io.github.nokse22.Exhibit`?
If you want you can also test the wayland version with the [nightly build](https://github.com/Nokse22/Exhibit/actions/runs/9454422930) and see if it works.

**Comment by theksepyro** [comment]
I have tried launching it through the terminal in that way, and it did not change my result. I still have just a black screen.

My current setup is on X11, so I won't be able to test the wayland version on my system at this time unfortunately.
<details><summary>Details</summary>
<p>

![image](https://github.com/Nokse22/Exhibit/assets/42880340/88fc1cc8-c0dc-4e2e-87c9-0fb2da900711)


</p>
</details>

**Comment by Nokse22** [comment]
If there is a black screen on wayland `GDK_DEBUG=gl-glx` should fix it.

**Comment by Damond5** [comment]
Just arrived home.

Can confirm, using GDK_DEBUG=gl-disable-gles or GDK_DEBUG=gl-prefer-gl, gives a black screen, instead of the error.

No output in terminal at all.

I tried enabling wayland session for gnome, but unfortunately it seems the wayland session was disabled for good reason, cause it was broken, so I havent been able to test with the wayland version either.
________________________________
Fra: Nokse22 ***@***.***>
Sendt: 12. juni 2024 15:48
Til: Nokse22/Exhibit ***@***.***>
Cc: Damond5 ***@***.***>; Author ***@***.***>
Emne: Re: [Nokse22/Exhibit] Unable to create a GL context (Issue #14)


If there is a black screen on wayland GDK_DEBUG=gl-glx should fix it.

**Comment by NoTuxNoBux** [comment]
With the release from a few hours ago, I'm also seeing this issue if I enable Wayland support in Flatseal (without it, everything fails to load now according to the toast), but it looks like an upstream Flatpak runtime issue since it seems to be trying to use NVK for Vulkan, whilst I'm using NVIDIA-DRM on my host - I don't have the former installed on my host machine, but perhaps it is in the Flatpak runtimes now:

```
╰─ LANG=C GDK_DEBUG=gl-glx io.github.nokse22.Exhibit Logo_MrWatts.glb                                                                     ─╯
Gsk-Message: 14:38:59.058: Failed to realize renderer of type 'GskNglRenderer' for surface 'GdkWaylandToplevel': Trying to use EGL, but X11 GLX is already in use

Gsk-Message: 14:38:59.058: Failed to realize renderer of type 'GskGLRenderer' for surface 'GdkWaylandToplevel': Trying to use EGL, but X11 GLX is already in use

DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.

(exhibit:2): Gdk-CRITICAL **: 14:39:01.393: Vulkan: ../src/nouveau/vulkan/nvk_physical_device.c:1109: VK_ERROR_INCOMPATIBLE_DRIVER
Traceback (most recent call last):
  File "/app/share/exhibit/exhibit/window.py", line 232, in on_realize
    self.gl_area.get_context().make_current()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'make_current'
```

I saw similar issues when you install `vulkan-nouveau` in Arch but are actually running on nvidia-drm when using tools such as `vulkaninfo`, hence the suspicion that it's somehow trying to force NVK because it's installed in the runtime despite it not being actually usable.

**Comment by Nokse22** [comment]
The Flathub version is not supposed to work in Wayland, if you want you can try the Wayland builds in the actions page. gl-glx might fix the black screen if you use the app in Xwayland.

**Comment by NoTuxNoBux** [comment]
FWIW, the (new) issue I had on GNOME Wayland is now fixed on 1.2.0.

**Comment by theksepyro** [comment]
I am no longer getting a black screen with the latest update when I use the 
>GDK_DEBUG=gl-prefer-gl
environment variable.

**Comment by RedAuburn** [comment]
the var also fixed it for me 👍️ has the GTK/nvidia bug been reported upstream?

**Comment by Nokse22** [comment]
It's great to hear that it is now working, I have tried setting this environment variable in the app, but if it works only after adding it I might need to do something more.

> has the GTK/nvidia bug been reported upstream?

Yes it has been reported already.
It's known issue that nvidia's EGL driver cannot switch between GL and GLES, so you need to tell Gtk to use GL before running.
