### ISSUE TITLE
Include some HDRIs by default

### ISSUE THREAD

**Issue by RedAuburn** [Nokse22/Exhibit#21]
It'd be nice to include one or two low-res HDRIs by default.
Also, when loading an HDRI either HDRI lighting should be automatically enabled, or the user should be prompted to enable it.

Maybe a display like this?

![exhibit concept](https://github.com/Nokse22/Exhibit/assets/26939824/fcc99d91-6cd1-474c-97bf-777873becdf3)

**Comment by Nokse22** [comment]
It could be a nice addition, will try to add it in the next release.
