### ISSUE TITLE
Feature request: Open model externally

### ISSUE THREAD

**Issue by cassidyjames** [Nokse22/Exhibit#22]
I absolutely _love_ Exhibit, and it instantly became part of my 3D printing workflow. One thing that would make it a bit more smooth would be to have a button to open the currently-loaded file with another app.

My use case is that I want to set Exhibit as the default app for 3D model files so I can easily preview them when I open them from the file browser, Firefox's downloads UI, etc. But sometimes I then want to pop it open in Cura or another 3D printing slicer—it would be nice to have a little “Open With…” button in the headerbar somewhere that spawns the UI to ask which app to open it with.

I believe this should be able to be implemented with [org.freedesktop.portal.OpenURI.OpenFile](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.OpenURI.html#org-freedesktop-portal-openuri-openfile), passing `true` for the `ask` option.

**Comment by cassidyjames** [comment]
More specifically, this should be the Python docs. :) http://lazka.github.io/pgi-docs/#Xdp-1.0/classes/Portal.html#Xdp.Portal.open_uri

**Comment by Nokse22** [comment]
Thank you very much!

It is a good idea, I will definitely be adding it in the next release.
