### ISSUE TITLE
Could not create a GL context

### ISSUE THREAD

**Issue by luzz-dev** [Nokse22/Exhibit#31]
For some reason the f3d_viewer.py that comes bundled with the program is **not able to create a GL context** and therefore the screen of the viewer area goes black.

I tried compiling it, here is the error:

`10:58:52 (f3d_viewer.py:225) CRITICAL: Could not create GL context`

I installed f3d from their flatpak repo yet that one seems to work fine at displaying models.

Here is my setup (I am using **x11** with an **Nvidia GPU**):

```
OS: Fedora Linux 40 (Workstation Edition) x86_64
Kernel: Linux 6.10.3-200.fc40.x86_64
Display (VG27A): 2560x1440 @ 120 Hz in 27″ [External] *
Display (VG27A): 2560x1440 @ 120 Hz in 27″ [External]
DE: GNOME 46.4
WM: Mutter (X11)
Theme: Adwaita [GTK2/3/4]
CPU: 11th Gen Intel(R) Core(TM) i5-11400F (12) @ 4.40 GHz
GPU: NVIDIA GeForce RTX 3060 [Discrete]
Memory: 15.48 GiB
Swap: 8.00 GiB
```

Here is the complete log: [builder.log](https://github.com/user-attachments/files/16597100/builder.log)

![image](https://github.com/user-attachments/assets/0128c62e-65bf-481d-af6e-a0827172471c)

**Comment by Nokse22** [comment]
If you open the about dialog and then the troubleshooting>debugging information section, do you have GDK_DEBUG: gl-egl:gl-prefer-gl?

Also try to run `flatpak override --env=GDK_DEBUG=gl-prefer-gl io.github.nokse22.Exhibit`

This usually happens because Nvidia GPUs need to know to use GL instead of GLES before running the app and can't switch after

**Comment by luzz-dev** [comment]
> Also try to run `flatpak override --env=GDK_DEBUG=gl-prefer-gl io.github.nokse22.Exhibit` or make sure with Flatseal that you have set GDK_DEBUG=gl-egl and gl-prefer-gl
> Related #14

This fixed it. Thank you. Hope they fix this Nvidia bug upstream soon.
![image](https://github.com/user-attachments/assets/a81b68f4-ae3f-4914-878e-cd6b83c6be35)
