### ISSUE TITLE
exhibit flatpak associates with more file types than needed

### ISSUE THREAD

**Issue by rezad1393** [Nokse22/Exhibit#33]
when I install or even update it, the app associates with files types that are not related to the app.

the more obvious onesare mp4 video types and octect-unknown type (which is any file not associated to be opened by anything)

**Comment by Nokse22** [comment]
The app associate with `application/octet-stream` because I allow to try and open any type of file, on my system if I do open with there are a lot of available applications for any file type.

The mp4 video is strange could you run 'xdg-mime query filetype filename.mp4' to see what type of mime type it is?

For reference these are all the mime type the app associates with, some of them are installed by the app from this [file](https://github.com/Nokse22/Exhibit/blob/master/data/io.github.nokse22.Exhibit.mime.xml):
```
application/gml+xml
application/octet-stream
application/prs.wavefront-obj
application/vnd.3ds
application/vnd.abc
application/vnd.brep
application/vnd.dae
application/vnd.drc
application/vnd.exodus
application/vnd.fbx
application/vnd.ms-3mfdocument
application/vnd.off
application/vnd.ply
application/vnd.pts
application/vnd.splat
application/vnd.step
application/vnd.usd
application/vnd.usdc
application/vnd.vdb
application/vnd.vdbMimeType=text/plain
application/vnd.vti
application/vnd.vtk
application/vnd.vtm
application/vnd.vtp
application/vnd.vtr
application/vnd.vts
application/vnd.vtu
application/vnd.x
image/tiff
image/vnd.dxf
image/x-3ds
model/3mf
model/gltf+json
model/gltf-binary
model/gltf-json
model/iges
model/obj
model/step
model/stl
model/vnd.usda
model/vnd.usdz+zip
model/x-other
text/plain
text/vnd.abc
```

**Comment by rezad1393** [comment]
> The mp4 video is strange could you run `xdg-mime query filetype filename.mp4` to see what mime type it is?
video/mp4




> The app associate with `application/octet-stream` because I allow to try and open any type of file, on my system if I do open with there are a lot of available applications for any file type.

I didn't quite get that, but I think you meant you need it on your personal computer so you don't have to go through list of app every time you want to open a file with this app.

but this makes life hell for others.
there are a lot of files that are application/octet-stream and double clicking on them would open them with this app which is not a good thing.

the app should not  be set to open a file that is not know to it and if a user want to they can open it manually.

**Comment by Nokse22** [comment]
> I didn't quite get that, but I think you meant you need it on your personal computer so you don't have to go through list of app every time you want to open a file with this app.

I meant just as an alternative between all the other apps

You're right, I should be able to remove `application/octet-stream` because I have installed all the possible mime type.

What kind of files do you have that are `application/octet-stream` for curiosity?

**Comment by Nokse22** [comment]
Still strange it opens mp4 even if it has the correct mime type

**Comment by rezad1393** [comment]
> Still strange it opens mp4 even if it has the correct mime type

should I say told you so?
I think it also opened other videos file or image file (I don't remember) and I removed them in last installs.
what I do remember is that it set itself as one of them app to open a lot of mimes that were NOT related to it.



> You're right, I should be able to remove `application/octet-stream` because I have installed all the possible mime type.

thanks.



> What kind of files do you have that are `application/octet-stream` for curiosity?

I don't remember right now but one was a 'file.bash' bash script.

**Comment by Nokse22** [comment]
I have removed it 7032601

**Comment by rezad1393** [comment]
> I have removed it [7032601](https://github.com/Nokse22/Exhibit/commit/7032601cc960ccd8c5f73b222ddf760da0ed92df)

was mp4 (and maybe others) issue is gonna be fixed too?

**Comment by Nokse22** [comment]
I don't know because I can't reproduce it. Maybe on your computer there were no apps that registered to open some files so `Exhibit` was the only available option, then it should

**Comment by rezad1393** [comment]
I got a flatpak update of this app and again this app associated itself with unknown filetype.

**Comment by Nokse22** [comment]
What do you mean unknown? Do they have a mime type using the command mentioned in a previous message? If I can understand exactly what mime type they are it might be useful.

**Comment by rezad1393** [comment]
> What do you mean unknown? Do they have a mime type using the command mentioned in a previous message? If I can understand exactly what mime type they are it might be useful.

I again forgot to check which file it was but they are usually torrent download incomplete files.

but right now this file is also associated  with:
RAR archive data, v4, os: Win32, flags: RecoveryRecordPresent

also it is associated with:
pdfs,mp3,ogg files.

**Comment by rezad1393** [comment]
even executables.....
![Screenshot_20240928_234549-1](https://github.com/user-attachments/assets/4f36320a-ff8d-468a-9ac8-aa2872315765)

**Comment by Nokse22** [comment]
What is the mime type?

**Comment by rezad1393** [comment]
xdg-mime query filetype magnetico                    
application/x-executable

**Comment by rezad1393** [comment]
> What is the mime type using `xdg-mime query filetype`?

xdg-mime query filetype magnetico                    
application/x-executable

**Comment by rezad1393** [comment]
why this app associate with 
 ./1.spc: Unicode text, UTF-8 text, with very long lines (1926)
mp3s?
pdfs?


I removed this app until this get fixed.
it is a good app for simple viewing 3d model, but it messes with my filetypes a lot.

**Comment by Nokse22** [comment]
I really don't know, you can check yourself the mime types the app associates with. Maybe there is a bug somewhere else.

**Comment by rezad1393** [comment]
> I really don't know, you can check yourself the mime types the app associates with. Maybe there is a bug somewhere else.

how do I do that ?
it is a flatpak app.

**Comment by Nokse22** [comment]
I am releasing a new version, maybe it gets fixed now.

**Comment by rezad1393** [comment]
> I am releasing a new version, maybe it gets fixed now.

did you find the cause?
if not then it will be like last time.

but I will wait and after new version I re-install it so maybe it gets fixed....

**Comment by Nokse22** [comment]
I accidentally added `octet-stream` back in another commit after removing it :facepalm:, but if this doesn't fix the issue I don't know what to do

**Comment by rezad1393** [comment]
did the new release fixed it?
I dont see the bug anymore.

**Comment by Nokse22** [comment]
Yes, the new release fixed it. Good to know!
