### ISSUE TITLE
error: Exhibit 1.4.0 doesn't work

### ISSUE THREAD

**Issue by juliangrubio** [Nokse22/Exhibit#34]
- flatpak install io.github.nokse22.Exhibit

Buscando coincidencias…

Permisos de io.github.nokse22.Exhibit:
    ipc   fallback-x11   wayland   x11   dri

        ID                                         Rama             Op           Remoto            Descarga
 1. [✓] io.github.nokse22.Exhibit.Locale           stable           i            flathub             6,0 kB / 23,6 kB
 2. [✓] io.github.nokse22.Exhibit                  stable           i            flathub           133,1 MB / 143,7 MB

Instalación completada.

- flatpak run io.github.nokse22.Exhibit

01:04:33 (window.py:248) INFO: Added city.hdr
01:04:33 (window.py:248) INFO: Added meadow.hdr
01:04:33 (window.py:248) INFO: Added field.hdr
01:04:33 (window.py:248) INFO: Added sky.hdr
01:04:33 (window.py:554) INFO: Use color is: False
01:04:33 (window.py:573) INFO: Setting: translucency-support to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:573) INFO: Setting: tone-mapping to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:573) INFO: Setting: ambient-occlusion to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:573) INFO: Setting: anti-aliasing to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:573) INFO: Setting: hdri-ambient to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:573) INFO: Setting: light-intensity to 1.5
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 1.5
01:04:33 (window.py:573) INFO: Setting: show-edges to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:573) INFO: Setting: edges-width to 1.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 1.0
01:04:33 (window.py:573) INFO: Setting: point-sprites to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:573) INFO: Setting: point-size to 1.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 1.0
01:04:33 (window.py:573) INFO: Setting: model-metallic to 0.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 0.0
01:04:33 (window.py:573) INFO: Setting: model-roughness to 0.3
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 0.3
01:04:33 (window.py:573) INFO: Setting: model-opacity to 1.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 1.0
01:04:33 (window.py:573) INFO: Setting: comp to -1
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:496) DEBUG: Setting scivis component combo, selected: 0
01:04:33 (window.py:573) INFO: Setting: cells to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:496) DEBUG: Setting scivis component combo, selected: 0
01:04:33 (window.py:573) INFO: Setting: model-color to (1.0, 1.0, 1.0)
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: grid to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:573) INFO: Setting: grid-absolute to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:573) INFO: Setting: hdri-skybox to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:573) INFO: Setting: hdri-file to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:469) INFO: Setting hdri file row filename to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: blur-background to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:573) INFO: Setting: blur-coc to 20.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:477) INFO: Setting spin to 20.0
01:04:33 (window.py:573) INFO: Setting: bg-color to (1.0, 1.0, 1.0)
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:554) INFO: Use color is: False
01:04:33 (window.py:573) INFO: Setting: up to +Y
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:550) INFO: Loading file because load type or up changed
01:04:33 (window.py:482) INFO: Setting up direction combo to 3
01:04:33 (window.py:573) INFO: Setting: orthographic to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: texture-matcap to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: texture-base-color to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: emissive-factor to (1.0, 1.0, 1.0)
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: texture-emissive to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: texture-material to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: normal-scale to 1.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: texture-normal to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: point-type to sphere
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: volume to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: inverse to False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: final-shader to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: grid-unit to 0.0
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: grid-subdivisions to 10
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: grid-color to (0.0, 0.0, 0.0)
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:573) INFO: Setting: scalar to 
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:582) INFO: Setting: use-color to False
01:04:33 (window.py:554) INFO: Use color is: False
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to False
01:04:33 (window.py:582) INFO: Setting: point-up to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:582) INFO: Setting: auto-reload to True
01:04:33 (window.py:698) DEBUG: Checking for changed options from general
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:601) INFO: Setting: auto-best to True
01:04:33 (window.py:473) INFO: Setting switch to True
01:04:33 (window.py:601) INFO: Setting: load-type to None
01:04:33 (window.py:550) INFO: Loading file because load type or up changed
01:04:33 (window.py:601) INFO: Setting: sidebar-show to True
01:04:33 (window.py:462) INFO: Startup in 0.22609877586364746 seconds
Gdk-Message: 01:04:34.900: Error 71 (Error de protocolo) dispatching to Wayland display.

**Comment by Nokse22** [comment]
Could you try to run `flatpak override --env=GSK_RENDERER=ngl` now with the updated runtime GTK uses Vulkan by default and maybe there is an issue with your Vulkan driver.

**Comment by Nokse22** [comment]
I am closing it as it is a bug with the driver
