### ISSUE TITLE
Can't display BambuStudio 3MF files

### ISSUE THREAD

**Issue by hadess** [Nokse22/Exhibit#39]
Opening the 3MF file in the ZIP (GitHub wouldn't let me attach a 3MF file) displays nothing in the 3D view portion of the window. Other files and filetypes seem to work.

[Filament-Clip-GrandMas-Favorite-Classic-pack-of-8.zip](https://github.com/user-attachments/files/17334268/Filament-Clip-GrandMas-Favorite-Classic-pack-of-8.zip)

This was generated using BambuStudio.

It's supposed to look like this:
![image](https://github.com/user-attachments/assets/30be3521-64dd-407d-902c-4575394bf1b4)

**Comment by Nokse22** [comment]
3MF is supposed to work, I usually see them just fine (now I can't test yours). Sometimes for reasons unknown to me there are issues viewing some models see also #38. Can you see it with F3D official app?

**Comment by Nokse22** [comment]
Also could you try to run the app from the terminal and give me the output after opening the file.

`flatpak run io.github.nokse22.Exhibit`

**Comment by hadess** [comment]
> 3MF is supposed to work, I usually see them just fine (now I can't test yours). Sometimes for reasons unknown to me there are issues viewing some models see also #38. Can you see it with F3D official app?
> 
> https://flathub.org/en-GB/apps/io.github.f3d_app.f3d

F3D displays nothing. I can just see the 3-axis at the bottom right to tell me it's running and click dragging makes it move.

> Also could you try to run the app from the terminal and give me the output after opening the file.

```
Found a reader for "/run/user/1000/doc/60769463/Filament-Clip-GrandMas-Favorite-Classic-pack-of-8.3mf" : "3MF"
Loading 3D scene: /run/user/1000/doc/60769463/Filament-Clip-GrandMas-Favorite-Classic-pack-of-8.3mf

No animation available in this file
No camera available in this file

Scene Graph:
------------
3MF
 Object_2
 Object_3
 Object_4
 Object_5
 Object_6
 Object_7
 Object_8
 Object_9


Scene bounding box: 1,-1,1,-1,1,-1

Camera position: -0,-1,-0
Camera focal point: 0,0,0
Camera view up: 0,0,1
Camera view angle: 30


00:31:25 (window.py:601) INFO: Setting: load-type to 1
00:31:25 (window.py:871) DEBUG: on file opened
00:31:25 (window.py:554) INFO: Use color is: False
```

**Comment by mwestphal** [comment]
> Scene Graph:
> ------------
> 3MF
> ...
> Scene bounding box: 1,-1,1,-1,1,-1

This means the file is read and the individual elements are detected BUT the geometry of the element is read has being completely empty. F3D is not able to show anything.

This can be a F3D bug, a Assimp bug or an issue in your file.

However, https://3dviewer.net/ is also not able to open your file, and it does not depend on F3D or assimp, so my guess would be a file issue.

**Comment by snoyer** [comment]
> However, [3dviewer.net](https://3dviewer.net/) is also not able to open your file, and it does not depend on F3D or assimp, so my guess would be a file issue.

The file opens in Prusa Slicer, however the objects are some sort of references/instantiations of a single model/mesh so it's possible that the file is fine but assimp doesn't handle that kind of indirection properly (or maybe that's an extension of the format?)

**Comment by Nokse22** [comment]
If you make a project in Bambu Studio and do `File>Save Project As` and save it as `.3mf` Exhibit won't open it, but doing `File>Export>Export Generic 3MF` the file can be opened. So I think it's not a simple `.3mf` file, but there is something more added by Bambu Studio or Prusa Slicer (since Bambu Studio is based on Prusa Slicer).

I have filled the bed with a model and the saved file doing `Export Generic 3MF` is 70 MB and the other one is only 3 MB so there is definitely something going on.

**Comment by snoyer** [comment]
> If you make a project in Bambu Studio and do `File>Save Project As` and save it as `.3mf` Exhibit won't open it, but doing `File>Export>Export Generic 3MF` the file can be opened. So I think it's not a simple `.3mf` file, but there is something more added by Bambu Studio or Prusa Slicer (since Bambu Studio is based on Prusa Slicer).

Same with Prusa Slicer, you can re-export the original file, it goes from 300kB to 2.2MB, and F3D/Exhibit can open this one

> I have filled the bed with a model and the saved file doing `Export Generic 3MF` is 70 MB and the other one is only 3 MB so there is definitely something going on.

Definitely references vs hardcoded copies of the meshes, the `.3mf` file can be opened as an archive if anyone is curious

**Comment by Nokse22** [comment]
> Definitely references vs hardcoded copies of the meshes, the .3mf file can be opened as an archive if anyone is curious

![Screenshot from 2024-10-11 10-24-53](https://github.com/user-attachments/assets/0154f31c-79fe-4a55-ab76-be9f2e136ec1)

That's it. Maybe it could be reported

**Comment by hadess** [comment]
I wasn't expecting to see this flurry of activity so quickly. Do you want me to file a separate bug in another repo, and which one would it be (F3D, assimp)?

**Comment by snoyer** [comment]
> I wasn't expecting to see this flurry of activity so quickly. Do you want me to file a separate bug in another repo, and which one would it be (F3D, assimp)?

Best would be to report to assimp as (the most F3D could do at this point would be to add a warning when finding "empty" objects) but you'd need a way for them to reproduce independently at their level...

I think if you should be able to create a second version of your file using copies (using the save options @Nokse22 mentioned) and run `assimp export your-original-file-with-references.3mf converted1.glb` and `assimp export your-file-exported-with-copies.3mf converted2.glb` to reproduce the same bug (one file would be as expected and the other empty) outside of F3D/Exhibit so that the assimp people can look into it

**Comment by Nokse22** [comment]
You can also point them to this link of the official 3MF Consortium [example files](https://github.com/3MFConsortium/3mf-samples/tree/665e20dc4d7777fd4c9702bca86a2d4028440337/examples/production) all files open except for `cube_gears_prod_req.3mf` that in fact has a similar structure to the one generated by Bambu Studio

**Comment by hadess** [comment]
Issue filed, see reference just above this comment
