### ISSUE TITLE
Can I have some more info on configuration?

### ISSUE THREAD

**Issue by GideonWolfe** [Nokse22/Exhibit#43]
I would like to set some of the options of `exhibit` (such as colors) through the config file. The only reference I see to such functionality is [here](https://github.com/Nokse22/Exhibit/blob/89fd4c8d2faa01096db55d5045f8f144baae7597/help/C/configurations.page#L20), but I can't figure out for the life of me where that's actually supposed to be viewed natively, because I can't find it in the application or Flathub.

Anyways, I don't have a `io.github.nokse22.Exhibit` folder in `~/.var/app`, do I need to make that manually? When I click `Save Settings` in the application, nothing happens and no file seems to be generated.

Application is working great so far though! Thanks

**Comment by Nokse22** [comment]
Hello!

Those help pages can be viewed from the main menu > Help or by pressing `F1`.

When you save a configuration do you see it listed in the configurations menu (three dots menu in the sidebar) or when restarting the app?

If you have installed the app as Flatpak there should be that folder, but to find it you can also click on `Open HDRI Folder` in the configurations menu, then navigating back to `data` and there should be a `configurations` folder where you can place any json file with custom configurations.

If one of these configurations supports the file you are opening it will have priority over the standard ones.

In the `Help` pages you can also find the `Options` page where you can find what each option does even the ones without UI.

Here is a config for `.splat` files for example:

```
{
    "splat": {
        "name": "Splat",
        "formats": ".*(splat)",
        "view-settings": {
            "translucency-support": true,
            "tone-mapping": false,
            "ambient-occlusion": false,
            "anti-aliasing": false,
            "hdri-ambient": false,
            "light-intensity": 1.5,
            "show-edges": false,
            "edges-width": 1.0,
            "point-sprites": true,
            "point-size": 1.0,
            "model-metallic": 0.0,
            "model-roughness": 0.3,
            "model-opacity": 1.0,
            "comp": -2,
            "cells": false,
            "model-color": [
                1.0,
                1.0,
                1.0
            ],
            "grid": false,
            "grid-absolute": false,
            "hdri-skybox": false,
            "hdri-file": "",
            "blur-background": true,
            "blur-coc": 20.0,
            "bg-color": [
                1.0,
                1.0,
                1.0
            ],
            "up": "+Y",
            "orthographic": false,
            "texture-matcap": "",
            "texture-base-color": "",
            "emissive-factor": [
                1.0,
                1.0,
                1.0
            ],
            "texture-emissive": "",
            "texture-material": "",
            "normal-scale": 1.0,
            "texture-normal": "",
            "point-type": "gaussian",
            "volume": false,
            "inverse": false,
            "final-shader": "",
            "grid-unit": 0.0,
            "grid-subdivisions": 10,
            "grid-color": [
                0.0,
                0.0,
                0.0
            ],
            "scalar": ""
        },
        "other-settings": {
            "use-color": false,
            "point-up": false,
            "auto-reload": true
        }
    }
}
```

**Comment by GideonWolfe** [comment]
Thanks for the speedy reply!

I can't seem to locate this "Main Menu" UI you speak of... Maybe it has something to do with Hyprland trying to hide it? My entire window looks like this

![image](https://github.com/user-attachments/assets/ad8311bb-3e44-47b2-bfa1-15b86ba8fb30)

`F1` has no effect either...

In terms of installation method, I am running NixOS and the package was installed according to the script [here](https://github.com/NixOS/nixpkgs/blob/nixos-24.11/pkgs/by-name/ex/exhibit/package.nix). Seems like the python program is being built directly and not a flatpak.

I'm a bit confused by the "Save Configuration" UI because the button has no visible feedback so I'm not sure where it's actually saving the file, which it seems to be since I was messing with the colors manually.

My main goal at first is to just change some of the colors, I don't have any file-specific requirements. I would like to 

* Change background color for skybox
* Change color of grid lines
* Change color of axis lines
* Change color of model

**Comment by Nokse22** [comment]
Oh, now I understand, this is version `1.2.0` of Exhibit, custom configurations have been added later. Now Exhibit is on version `1.4.1`

**Comment by GideonWolfe** [comment]
Ah, that explains it. I'll wait for an update upstream :)
