### ISSUE TITLE
Support (basic) camera movement controls such as WASD and/or arrow keys

### ISSUE THREAD

**Issue by NoTuxNoBux** [Nokse22/Exhibit#7]
Currently you can use the mouse to rotate, and the mouse scroll wheel to zoom. It would be neat if there were some simple 'fly' keys that move the camera such as WASD and/or the arrow keys. This is especially helpful with large models, such as those of buildings, where you want to go 'inside'.

In combination with this, it would be handy if the right-mouse button could let you look around instead of rotating around the model.

**Comment by Nokse22** [comment]
I will add it!
